spring:
  redis:
    cluster:
      nodes: 11.11.160.68:6379,11.11.160.68:6381,11.11.160.75:6383
      max-redirects: 10
    password:
    timeout: 0
    jedis:
      pool:
        max-active: -1
        max-wait: -1
        max-idle: 10
        min-idle: 3 

      

edw: 
  sdp:
    redis: 
     timeoutMsecs: 10000
     lockSuf: _redis_lock